# NEDEN NUMPY

In [7]:
import numpy as np

In [9]:
a = np.array([1,2,4,5,4])

In [11]:
type(a)

numpy.ndarray

In [14]:
#Sfiridan array oluşturma

In [15]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.full((3,3),3,dtype=int)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [20]:
np.arange(3,31,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [21]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
np.random.normal(10,4,(3,4))
#rastgele ama dağılımı belirtildi

array([[ 5.84552351, 13.6269526 ,  7.69340741, 11.83716452],
       [ 4.56323313,  6.06401669, 10.0078148 , 11.20837461],
       [ 9.93654514,  9.99722313, 13.73365425, 14.76210876]])

In [24]:
np.random.randint(0,10,(3,3))

array([[1, 9, 2],
       [9, 8, 0],
       [0, 4, 2]])

# Özellikleri
* ndim
* shape
* size
* dtype

In [26]:
a= np.random.randint(10,size=10)

In [27]:
a.ndim

1

In [28]:
a.shape

(10,)

In [29]:
a.dtype

dtype('int32')

In [30]:
b = np.random.randint(10,size=(3,5))

In [31]:
b

array([[9, 0, 3, 1, 6],
       [8, 3, 8, 2, 4],
       [9, 7, 8, 8, 7]])

In [32]:
b.ndim

2

In [33]:
b.shape

(3, 5)

In [34]:
b.dtype

dtype('int32')

In [35]:
b.size

15

# Yeniden Şekillendirme

In [36]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a = np.arange(1,10)

In [39]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a.ndim

1

In [42]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# birleştirme

In [46]:
x = np.array([1,2,3])
y= np.array([4,5,6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [47]:
z = np.array([7,8,9])


In [48]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# iki boyut

In [51]:
a = np.array([[1,2,3],
            [4,5,6]])

In [52]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma

In [54]:
x = np.array([1,2,3,99,99,3,2,1])

In [55]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [57]:
a = np.split(x,[3,5])

In [58]:
a,b,c = np.split(x,[3,5])

In [59]:
a

array([1, 2, 3])

In [60]:
b

array([99, 99])

In [61]:
c

array([3, 2, 1])

In [62]:
# iki boyutlu ayırma

In [63]:
m =np.arange(16).reshape(4,4)

In [64]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
ust ,alt = np.vsplit(m,[2])

In [69]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# SIRALAMA

In [74]:
v = np.array([2,1,4,3,5])

In [75]:
v

array([2, 1, 4, 3, 5])

In [76]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [80]:
# iki boyutlu array sırala

In [81]:
np.random.normal(20,5,(3,3))

array([[24.96188561, 24.4703511 , 17.4711095 ],
       [20.67036571, 22.42339782, 18.70976272],
       [ 9.72636401, 18.99262847, 19.54557714]])

In [82]:
np.sort(m,axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
np.sort(m,axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# INDEX İLE ELEMANA ERİŞ

In [84]:
a = np.random.randint(10,size=10)

In [85]:
a

array([5, 6, 3, 4, 2, 8, 9, 1, 2, 0])

In [86]:
a[0]=100

In [95]:
m = np.random.randint(10,size=(3,5))

In [96]:
m

array([[1, 9, 0, 2, 6],
       [4, 4, 3, 3, 0],
       [1, 5, 2, 7, 8]])

In [97]:
m[0,0]

1

In [98]:
m[1,1]

4

In [99]:
m[1,2]

3

In [100]:
m [1,4]=2.2

In [101]:
m

array([[1, 9, 0, 2, 6],
       [4, 4, 3, 3, 2],
       [1, 5, 2, 7, 8]])

# Slicing ile elemane eriş

In [102]:
a = np.arange(20,30)

In [103]:
a[0:3]

array([20, 21, 22])

In [104]:
a[:3]

array([20, 21, 22])

In [105]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [106]:
a[1::2]

array([21, 23, 25, 27, 29])

In [107]:
a[0::2]

array([20, 22, 24, 26, 28])

In [109]:
a[0::3]

array([20, 23, 26, 29])

In [110]:
# iki boyutlu slice


In [111]:
m = np.random.randint(10,size=[5,5])

In [112]:
m

array([[1, 8, 1, 4, 0],
       [1, 7, 9, 3, 1],
       [8, 8, 3, 7, 2],
       [0, 5, 2, 7, 2],
       [0, 6, 7, 2, 4]])

In [113]:
m[:,0]

array([1, 1, 8, 0, 0])

In [114]:
m[:,1]

array([8, 7, 8, 5, 6])

In [115]:
m[0,:]

array([1, 8, 1, 4, 0])

In [116]:
m[1,:]

array([1, 7, 9, 3, 1])

In [117]:
m

array([[1, 8, 1, 4, 0],
       [1, 7, 9, 3, 1],
       [8, 8, 3, 7, 2],
       [0, 5, 2, 7, 2],
       [0, 6, 7, 2, 4]])

In [118]:
m[0:2,0:3]

array([[1, 8, 1],
       [1, 7, 9]])

In [119]:
m[::,:2]

array([[1, 8],
       [1, 7],
       [8, 8],
       [0, 5],
       [0, 6]])

In [120]:
m[:,0:2]

array([[1, 8],
       [1, 7],
       [8, 8],
       [0, 5],
       [0, 6]])

In [121]:
m[1:3,0:2]

array([[1, 7],
       [8, 8]])

In [122]:
m

array([[1, 8, 1, 4, 0],
       [1, 7, 9, 3, 1],
       [8, 8, 3, 7, 2],
       [0, 5, 2, 7, 2],
       [0, 6, 7, 2, 4]])

# Alt küme üzerinde işlem

In [123]:
a = np.random.randint(10,size=(5,5))

In [124]:
a

array([[5, 3, 9, 2, 8],
       [9, 6, 0, 5, 2],
       [4, 2, 3, 1, 6],
       [8, 7, 3, 6, 4],
       [2, 1, 8, 9, 2]])

In [126]:
alt_a = a[0:3,0:2]

In [127]:
alt_a

array([[5, 3],
       [9, 6],
       [4, 2]])

In [128]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [129]:
alt_a

array([[99999,     3],
       [    9,   888],
       [    4,     2]])

In [130]:
a

array([[99999,     3,     9,     2,     8],
       [    9,   888,     0,     5,     2],
       [    4,     2,     3,     1,     6],
       [    8,     7,     3,     6,     4],
       [    2,     1,     8,     9,     2]])

In [131]:
ma = np.random.randint(10,size=(5,5))

In [132]:
alt_b = m[0:3,0:2].copy()

In [133]:
alt_b

array([[1, 8],
       [1, 7],
       [8, 8]])

In [134]:
alt_b[0,0]=9999

In [135]:
alt_b

array([[9999,    8],
       [   1,    7],
       [   8,    8]])

In [136]:
m

array([[1, 8, 1, 4, 0],
       [1, 7, 9, 3, 1],
       [8, 8, 3, 7, 2],
       [0, 5, 2, 7, 2],
       [0, 6, 7, 2, 4]])

# FANCY İNDEX İLE ELEMANLARA ERİŞ

In [139]:
v = np.arange(0,30,3)

In [140]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [141]:
v[1]

3

In [142]:
v[3]

9

In [143]:
v[5]

15

In [146]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [147]:
alt_getir = [1,3,5]

In [148]:
v[alt_getir]

array([ 3,  9, 15])

In [149]:
#iki boyutlu

In [153]:
m = np.arange(9).reshape((3,3))

In [154]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [156]:
m[satir,sutun]

array([1, 5])

In [157]:
# basit index ile fancy index

In [158]:
m[0,[1,2]]

array([1, 2])

In [159]:
#slice

In [160]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu eleman işlemleri

In [161]:
v = np.array([1,2,3,4,5])

In [162]:
v>5

array([False, False, False, False, False])

In [163]:
v[v>5]

array([], dtype=int32)

In [164]:
v<3

array([ True,  True, False, False, False])

In [165]:
v[v<3]

array([1, 2])

In [166]:
v[v!=3]

array([1, 2, 4, 5])

In [167]:
v

array([1, 2, 3, 4, 5])

In [168]:
v*2

array([ 2,  4,  6,  8, 10])

In [169]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [170]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [171]:
v**22

array([          1,     4194304,  1316288537,           0, -2094601527],
      dtype=int32)

# Matematiksesl işlemler giriş

In [172]:
v = np.array([1,2,3,4,5])

In [173]:
v

array([1, 2, 3, 4, 5])

In [174]:
v-1

array([0, 1, 2, 3, 4])

In [175]:
v

array([1, 2, 3, 4, 5])

In [176]:
# ufunc

In [178]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [179]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [180]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [181]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [182]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [184]:
np.absolute(np.array([-3,-5,-6]))

array([3, 5, 6])

In [185]:
np.sin(360)

0.9589157234143065

In [186]:
np.cos(180)

-0.5984600690578581

In [187]:
v = np.array([1,2,3])

In [188]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [189]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [192]:
#cheatSheet

# istatiksel hesaplar

In [193]:
np.mean(v,axis=0)

2.0

np.arange(5.10)

In [195]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])